{
 "title": "Scanners",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Dispatcher Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_inprogress_requests{serving_knative_dev_service=\"dispatcher\"})"
    }
   ]
  },
  {
   "title": "Result Processor Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_inprogress_requests{serving_knative_dev_service=\"result-processor\"})"
    }
   ]
  },
  { "title": "Logs", "type": "logs", "gridPos": { "h": 15, "w": 8, "x": 16, "y": 0 } },
  {
   "title": "DKIM Scanner Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_inprogress_requests{serving_knative_dev_service=\"dkim-scanner\"})"
    }
   ]
  },
  {
   "title": "DMARC Scanner Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_inprogress_requests{serving_knative_dev_service=\"dmarc-scanner\"})"
    }
   ]
  },
  {
   "title": "SSL Scanner Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_inprogress_requests{serving_knative_dev_service=\"ssl-scanner\"})"
    }
   ]
  },
  {
   "title": "HTTPS Scanner Traffic",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_inprogress_requests{serving_knative_dev_service=\"https-scanner\"})"
    }
   ]
  }
 ]
}