apiVersion: batch/v1
kind: Job
metadata:
  name: uptime-sync
  namespace: uptime
spec:
  template:
    metadata:
      labels:
        job: uptime-sync
    spec:
      containers:
        - name: sync-sidecar
          image: northamerica-northeast1-docker.pkg.dev/track-compliance/tracker/uptime-sync:master-f5c3686-1780497120 # {"$imagepolicy": "flux-system:uptime-sync"}
          command: ["python", "/app/sync-gatus-config.py"]
          env:
            - name: ARANGO_URL
              valueFrom:
                secretKeyRef:
                  name: uptime
                  key: ARANGO_URL
            - name: ARANGO_DATABASE
              valueFrom:
                secretKeyRef:
                  name: uptime
                  key: ARANGO_DATABASE
            - name: ARANGO_USERNAME
              valueFrom:
                secretKeyRef:
                  name: uptime
                  key: ARANGO_USERNAME
            - name: ARANGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: uptime
                  key: ARANGO_PASSWORD
            - name: GATUS_CONFIG_PATH
              value: /config/config.yaml
            - name: NOTIFICATION_API_KEY
              valueFrom:
                secretKeyRef:
                  name: uptime
                  key: NOTIFICATION_API_KEY
            - name: NOTIFICATION_API_URL
              valueFrom:
                secretKeyRef:
                  name: uptime
                  key: NOTIFICATION_API_URL
            - name: SERVICE_ACCOUNT_EMAIL
              valueFrom:
                secretKeyRef:
                  name: uptime
                  key: SERVICE_ACCOUNT_EMAIL
            - name: NOTIFICATION_UPTIME_ALERT_ID
              valueFrom:
                secretKeyRef:
                  name: uptime
                  key: NOTIFICATION_UPTIME_ALERT_ID
          volumeMounts:
            - name: gatus-config
              mountPath: /config
          resources:
            limits:
              cpu: 100m
              memory: 128Mi
            requests:
              cpu: 25m
              memory: 64Mi
          securityContext:
            runAsGroup: 1000
            runAsUser: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            privileged: false
            runAsNonRoot: true
      restartPolicy: OnFailure
