steps:
  - name: 'docker:29'
    id: start_arango
    entrypoint: 'ash'
    args:
      [
        '-c',
        'docker run -d --network=cloudbuild -p=8529:8529 -e ARANGO_ROOT_PASSWORD=$_DB_PASS --name=arangodb arangodb/arangodb:3.12.1',
      ]

  - name: mikewilliamson/wait-for
    id: wait
    args: ['arangodb:8529']

  - name: 'docker:29'
    id: build-test-image
    dir: services/domain-cleanup
    args: ['build', '--target=test', '-t', 'test-image', '.']

  - name: 'test-image'
    id: run-lint
    dir: /app
    entrypoint: npm
    args: ['run', 'lint']

  - name: 'test-image'
    id: run-tests
    dir: /app
    entrypoint: npm
    args: ['test']
    env:
      - DB_URL=$_DB_URL
      - DB_PASS=$_DB_PASS
      - DB_NAME=$_DB_NAME
      - UNCLAIMED_ORG_ID=$_UNCLAIMED_ORG_ID

  - name: 'docker:29'
    id: generate-image-name
    entrypoint: 'ash'
    dir: services/domain-cleanup
    args:
      - '-c'
      - |
        echo 'northamerica-northeast1-docker.pkg.dev/track-compliance/tracker/services/domain-cleanup:'"$(echo $BRANCH_NAME | sed 's/[^a-zA-Z0-9]/-/g')-$SHORT_SHA-$(date +%s)" > /workspace/imagename

  - name: 'docker:29'
    id: build
    entrypoint: 'ash'
    dir: services/domain-cleanup
    args:
      - '-c'
      - |
        image=$(cat /workspace/imagename)
        docker build -t $image .

  - name: 'docker:29'
    id: push-if-master
    entrypoint: 'ash'
    dir: services/domain-cleanup
    args:
      - '-c'
      - |
        if [[ '$BRANCH_NAME' == 'master' ]]
        then
          image=$(cat /workspace/imagename)
          docker push $image
        else
          exit 0
        fi
