steps:
  - name: 'docker:29'
    id: generate-image-name
    entrypoint: 'ash'
    dir: services/cvd-enrollment
    args:
      - '-c'
      - |
        echo 'northamerica-northeast1-docker.pkg.dev/track-compliance/tracker/services/cvd-enrollment:'"$(echo $BRANCH_NAME | sed 's/[^a-zA-Z0-9]/-/g')-$SHORT_SHA-$(date +%s)" > /workspace/imagename

  - name: 'docker:29'
    id: build-test-image
    dir: services/cvd-enrollment
    args: ['build', '--target=test', '-t', 'test-image', '.']

  - name: 'test-image'
    id: run-tests
    dir: services/cvd-enrollment
    entrypoint: 'python3'
    args: [ '-m', 'pytest', 'tests/', '-v']

  - name: 'docker:29'
    id: build-production-image
    entrypoint: 'ash'
    dir: services/cvd-enrollment
    args:
      - '-c'
      - |
        image=$(cat /workspace/imagename)
        docker build -t $image .

  - name: 'docker:29'
    id: push-enrollment-if-master
    entrypoint: 'ash'
    dir: services/cvd-enrollment
    args:
      - '-c'
      - |
        if [[ '$BRANCH_NAME' == 'master' ]]
        then
          image=$(cat /workspace/imagename)
          docker push $image
        else
          exit 0
        fi
