export const data = [
  {
    month: 'June',
    year: 2020,
    categoryTotals: {
      fullPass: 2685,
      passSpfOnly: 69,
      passDkimOnly: 69,
      fail: 63,
      total: 2886,
      __typename: 'CategoryTotals',
    },
    __typename: 'DmarcReportSummaryList',
  },
  {
    month: 'May',
    year: 2020,
    categoryTotals: {
      fullPass: 8331,
      passSpfOnly: 168,
      passDkimOnly: 168,
      fail: 570,
      total: 9237,
      __typename: 'CategoryTotals',
    },
    __typename: 'DmarcReportSummaryList',
  },
  {
    month: 'April',
    year: 2020,
    categoryTotals: {
      fullPass: 9862,
      passSpfOnly: 190,
      passDkimOnly: 192,
      fail: 603,
      total: 10847,
      __typename: 'CategoryTotals',
    },
    __typename: 'DmarcReportSummaryList',
  },
  {
    month: 'March',
    year: 2020,
    categoryTotals: {
      fullPass: 11942,
      passSpfOnly: 302,
      passDkimOnly: 302,
      fail: 1131,
      total: 13677,
      __typename: 'CategoryTotals',
    },
    __typename: 'DmarcReportSummaryList',
  },
  {
    month: 'February',
    year: 2020,
    categoryTotals: {
      fullPass: 4427,
      passSpfOnly: 254,
      passDkimOnly: 254,
      fail: 140,
      total: 5075,
      __typename: 'CategoryTotals',
    },
    __typename: 'DmarcReportSummaryList',
  },
  {
    month: 'January',
    year: 2020,
    categoryTotals: {
      fullPass: 3033,
      passSpfOnly: 938,
      passDkimOnly: 940,
      fail: 400,
      total: 5311,
      __typename: 'CategoryTotals',
    },
    __typename: 'DmarcReportSummaryList',
  },
  {
    month: 'December',
    year: 2019,
    categoryTotals: {
      fullPass: 1538,
      passSpfOnly: 906,
      passDkimOnly: 906,
      fail: 124,
      total: 3474,
      __typename: 'CategoryTotals',
    },
    __typename: 'DmarcReportSummaryList',
  },
  {
    month: 'November',
    year: 2019,
    categoryTotals: {
      fullPass: 1491,
      passSpfOnly: 1234,
      passDkimOnly: 1235,
      fail: 168,
      total: 4128,
      __typename: 'CategoryTotals',
    },
    __typename: 'DmarcReportSummaryList',
  },
  {
    month: 'October',
    year: 2019,
    categoryTotals: {
      fullPass: 1508,
      passSpfOnly: 1474,
      passDkimOnly: 1475,
      fail: 331,
      total: 4788,
      __typename: 'CategoryTotals',
    },
    __typename: 'DmarcReportSummaryList',
  },
  {
    month: 'September',
    year: 2019,
    categoryTotals: {
      fullPass: 599,
      passSpfOnly: 480,
      passDkimOnly: 481,
      fail: 158,
      total: 1718,
      __typename: 'CategoryTotals',
    },
    __typename: 'DmarcReportSummaryList',
  },
  {
    month: 'August',
    year: 2019,
    categoryTotals: {
      fullPass: 0,
      passSpfOnly: 0,
      passDkimOnly: 0,
      fail: 0,
      total: 0,
      __typename: 'CategoryTotals',
    },
    __typename: 'DmarcReportSummaryList',
  },
  {
    month: 'July',
    year: 2019,
    categoryTotals: {
      fullPass: 0,
      passSpfOnly: 0,
      passDkimOnly: 0,
      fail: 0,
      total: 0,
      __typename: 'CategoryTotals',
    },
    __typename: 'DmarcReportSummaryList',
  },
  {
    month: 'June',
    year: 2019,
    categoryTotals: {
      fullPass: 0,
      passSpfOnly: 0,
      passDkimOnly: 0,
      fail: 0,
      total: 0,
      __typename: 'CategoryTotals',
    },
    __typename: 'DmarcReportSummaryList',
  },
]
