"""empty message

Revision ID: 0a8fe5b09368
Revises: 0487ebd413ff
Create Date: 2020-03-05 14:18:09.837158

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a8fe5b09368'
down_revision = '0487ebd413ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('domains', 'scan_ssl')
    op.drop_column('domains', 'scan_mx')
    op.drop_column('domains', 'scan_spf')
    op.drop_column('domains', 'scan_https')
    op.drop_column('domains', 'scan_dmarc_psl')
    op.drop_column('domains', 'scan_dmarc')
    op.drop_column('domains', 'scan_dkim')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('scan_dkim', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('domains', sa.Column('scan_dmarc', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('domains', sa.Column('scan_dmarc_psl', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('domains', sa.Column('scan_https', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('domains', sa.Column('scan_spf', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('domains', sa.Column('scan_mx', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('domains', sa.Column('scan_ssl', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
