"""empty message

Revision ID: 2a25ac8483bc
Revises: c264f0905a36
Create Date: 2020-05-20 13:38:34.078690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "2a25ac8483bc"
down_revision = "c264f0905a36"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("email_validated", sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "email_validated")
    # ### end Alembic commands ###
