"""empty message

Revision ID: 342849bd4576
Revises: 2b3987bec90f
Create Date: 2020-07-06 07:27:50.018621

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "342849bd4576"
down_revision = "2b3987bec90f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dmarc_reports")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dmarc_reports",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column(
            "start_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "end_date", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "report",
            postgresql.JSONB(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("domain_id", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["domain_id"], ["domains.id"], name="dmarc_reports_domain_id_fkey"
        ),
        sa.PrimaryKeyConstraint("id", name="dmarc_reports_pkey"),
    )
    # ### end Alembic commands ###
