"""empty message

Revision ID: 4ba7ffac78cf
Revises: 96aba692bb38
Create Date: 2020-03-24 14:37:09.254650

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "4ba7ffac78cf"
down_revision = "96aba692bb38"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("dmarc_reports", sa.Column("domain_id", sa.Integer(), nullable=True))
    op.drop_constraint("dmarc_reports_id_fkey", "dmarc_reports", type_="foreignkey")
    op.create_foreign_key(
        "dmarc_reports_domain_id_fkey",
        "dmarc_reports",
        "domains",
        ["domain_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "dmarc_reports_domain_id_fkey", "dmarc_reports", type_="foreignkey"
    )
    op.create_foreign_key(
        "dmarc_reports_id_fkey", "dmarc_reports", "domains", ["id"], ["id"]
    )
    op.drop_column("dmarc_reports", "domain_id")
    # ### end Alembic commands ###
