"""empty message

Revision ID: 9e99f1ee15a8
Revises: 342849bd4576
Create Date: 2020-07-07 11:38:53.136103

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9e99f1ee15a8"
down_revision = "342849bd4576"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("password_reset_code", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "password_reset_code")
    # ### end Alembic commands ###
