"""empty message

Revision ID: 9fae6f7c6de1
Revises: eb19d38eec0f
Create Date: 2020-02-20 14:33:50.553877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "9fae6f7c6de1"
down_revision = "eb19d38eec0f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("user_name", sa.String(), nullable=True))
    op.drop_column("users", "user_email")
    op.drop_column("users", "username")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("username", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "users",
        sa.Column("user_email", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("users", "user_name")
    # ### end Alembic commands ###
