"""empty message

Revision ID: a1a5672bac39
Revises: c1f12c82fde1
Create Date: 2020-03-12 10:39:03.166636

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a1a5672bac39"
down_revision = "c1f12c82fde1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("organizations", sa.Column("acronym", sa.String(), nullable=True))
    op.drop_column("organizations", "organization")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "organizations",
        sa.Column("organization", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("organizations", "acronym")
    # ### end Alembic commands ###
