"""empty message

Revision ID: c1f12c82fde1
Revises: a1c98d5148a1
Create Date: 2020-03-11 07:12:41.723189

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c1f12c82fde1'
down_revision = 'a1c98d5148a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mx_scans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mx_scan', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['scans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mx_scans')
    # ### end Alembic commands ###
