"""empty message

Revision ID: c264f0905a36
Revises: b781fb62a115
Create Date: 2020-05-12 07:33:28.965455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c264f0905a36'
down_revision = 'b781fb62a115'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('slug', sa.String(), nullable=True))
    op.create_index(op.f('ix_domains_slug'), 'domains', ['slug'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_domains_slug'), table_name='domains')
    op.drop_column('domains', 'slug')
    # ### end Alembic commands ###
