"""empty message

Revision ID: c83b621d9ae7
Revises: 210111cbd5ae
Create Date: 2020-02-17 07:08:50.919563

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c83b621d9ae7'
down_revision = '210111cbd5ae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'scans', 'users', ['initiated_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'scans', type_='foreignkey')
    # ### end Alembic commands ###
