"""empty message

Revision ID: cf42b66dbc12
Revises: 4ba7ffac78cf
Create Date: 2020-03-30 08:03:05.845999

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf42b66dbc12'
down_revision = '4ba7ffac78cf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dmarc_scans', sa.Column('dmarc_phase', sa.Integer(), nullable=True))
    op.drop_column('domains', 'dmarc_phase')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('domains', sa.Column('dmarc_phase', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('dmarc_scans', 'dmarc_phase')
    # ### end Alembic commands ###
