"""empty message

Revision ID: d71a446b0f6f
Revises: 0487ebd413ff
Create Date: 2020-03-02 08:44:25.713589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "d71a446b0f6f"
down_revision = "0487ebd413ff"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("failed_login_attempt_time", sa.String(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "failed_login_attempt_time")
    # ### end Alembic commands ###
