"""empty message

Revision ID: e896f9a4cd32
Revises: ab1e9f54b481
Create Date: 2020-02-12 14:20:33.295738

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e896f9a4cd32'
down_revision = 'ab1e9f54b481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'user_role')
    # ### end Alembic commands ###
