"""empty message

Revision ID: eb19d38eec0f
Revises: 0b43b774e550
Create Date: 2020-02-18 07:47:41.897730

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "eb19d38eec0f"
down_revision = "0b43b774e550"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE scans ALTER COLUMN initiated_by TYPE INTEGER USING initiated_by::integer"
    )
    op.create_foreign_key(
        "fk_users_id_scans", "scans", "users", ["initiated_by"], ["id"]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("fk_users_id_scans", "scans", type_="foreignkey")
    op.alter_column(
        "scans",
        "initiated_by",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
