"""empty message

Revision ID: f95ba654a20b
Revises: ab1e9f54b481
Create Date: 2020-02-12 09:59:05.199085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f95ba654a20b'
down_revision = 'ab1e9f54b481'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('two_factor_auth', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'two_factor_auth')
    # ### end Alembic commands ###
